
% Master script for running bipolar analysis and figures

% Setup
setup_bipolar;
 
%% generate intermediate data files

%Run EachVsAll_cleaned2025; to start % performs BPRR analysis and saves intermediate data files for plotting

EachVsAll_cleaned2025;

%% Figure 1: Electrode coverages and distributions of bipolar pair distances
% Note, function requires:
    % fix_{components}_dist_tent_{patient}.mat
% which is generated by running EachVsAll_cleaned2025.m

%
bipolar_electrodemaps_2025_revised;

%% Figure 2: Linear bipolar re-referencing according to distance and linear BPRR analysis

bipolarexpedition_Linear_2025;

%% Figure 3: Omnidirectional BPRR (intact grids)

% run analysis save data for plotting for EC175 and EC183 (both have 16x16 subdural grid)
fig3_EachVsAll('EC175');
fig3_EachVsAll('EC183');
% saves as ECXXX_fig3_data.mat
% note, can run on any patients and component combination through
% EachVsAll_cleaned2025.m script

% plot figure 3
fig3_plot;

%% Figure 4: Relative changes in power from referential as function of BPRR distance

% Note, function requires:
    % fix_{components}_dist_tent_{patient}.mat
    % fix_{components}_tent_{patient}.mat
% which is generated by running EachVsAll_cleaned2025.m

EachVsAll_cleaned2025; % performs BPRR analysis and saves intermediate data files for plotting

% plot figure 4
bipolar_electrodemaps_2025_revised;

%% Figure 5: BPRR distance in STG during active listening

% run analysis and save data for patient plotting

bipolarexpedition_EachVsAll_StimSpeech;

% plot figure 5
fig5_out;

%% Figure 6: IED detection with HD vs subsampled

high_density_ecog_script;
postHocStats;

%% Figures 6: part B - specific subject 

high_density_ecog_script_ec133_abs_der_only;

%% Supplementary Linear figure (all patients individually)

linearSupp;










